### ISSUE TITLE
Tooltips.lua:399: bad argument #1 to 'gmatch' (string expected, got table)

### ISSUE THREAD

**Issue by Ookami313** [Nukme/InspectEquip#3] opened 2023-04-13 01:58 UTC
I've been receiving errors for the last bit, but I'm not totally sure what is setting them off. I think one is occurring after logging into the game and the other random occurs when I either pick up an item or mouse over an item in my inventory. Sorry for the vague explanations, though if i can get a better idea of when they are occurring I will update the ticket. Thanks.

12x InspectEquip/Src/Modules/Tooltips.lua:399: bad argument #1 to 'gmatch' (string expected, got table)
[string "=[C]"]: in function `gmatch'
[string "@InspectEquip/Src/Modules/Tooltips.lua"]:399: in function <InspectEquip/Src/Modules/Tooltips.lua:389>
[string "@InspectEquip/Src/Modules/Tooltips.lua"]:421: in function `AddToTooltip'
[string "@InspectEquip/Src/Modules/Tooltips.lua"]:433: in function `ParseItem'
[string "@InspectEquip/Src/Modules/Tooltips.lua"]:444: in function <InspectEquip/Src/Modules/Tooltips.lua:443>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
...
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@WorldQuestTab/Templates.lua"]:602: in function <WorldQuestTab/Templates.lua:534>
[string "@WorldQuestTab/Templates.lua"]:666: in function `AddQuestRewardsToTooltip'
[string "@WorldQuestTab/Dataprovider.lua"]:86: in function <WorldQuestTab/Dataprovider.lua:83>
[string "@WorldQuestTab/Dataprovider.lua"]:214: in function `LoadRewards'
[string "@WorldQuestTab/Dataprovider.lua"]:155: in function `Init'
[string "@WorldQuestTab/Dataprovider.lua"]:693: in function `AddQuest'
[string "@WorldQuestTab/Dataprovider.lua"]:659: in function `AddQuestsInZone'
[string "@WorldQuestTab/Dataprovider.lua"]:525: in function `OnUpdate'
[string "@WorldQuestTab/Dataprovider.lua"]:472: in function <WorldQuestTab/Dataprovider.lua:472>

Locals:
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = "[^;]+"
(*temporary) = "string expected, got table"

1x InspectEquip/Src/Modules/Core.lua:88: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@InspectEquip/Src/Modules/Core.lua"]:88: in function `IsPvPItem'
[string "@InspectEquip/Src/Modules/Inspect.lua"]:518: in function `GetItemData'
[string "@InspectEquip/Src/Modules/Core.lua"]:182: in function `GetItemSourceCategories'
[string "@InspectEquip/Src/Modules/Inspect.lua"]:281: in function `Inspect'
[string "@InspectEquip/Src/Modules/Inspect.lua"]:147: in function <InspectEquip/Src/Modules/Inspect.lua:144>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2897: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2740: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2605: in function <FrameXML/UIParent.lua:2601>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3207: in function <FrameXML/UIParent.lua:3186>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Dread"
(*temporary) = "string expected, got nil"

**Comment by Nukme** [comment] 2023-04-15 03:27
I'll try to fix this but it may take a while.

**Comment by Nukme** [comment] 2023-06-17 17:19
Sorry for the late fix. The latter lua error related to pvp affix should be fixed in the latest release. However, I couldn't reproduce the first lua error in build 10.1.0.50000. I may have missed the game version where this lua should happen or I'm not playing long enough for it to pop out.  Is it still a thing for you?

**Closed** 2023-06-28 16:24 UTC
